application: nocdportal
version: 7
runtime: python27
api_version: 1
threadsafe: yes
module: default
handlers:

- url: /resources
  static_dir: resources

- url: .*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: ssl
  version: latest
